name: bim
channels:
  - conda-forge
dependencies:
  - jupyter
  - numpy
  - scipy
  - python=3.10
  - ca-certificates
  - openssl
  - matplotlib
  - certifi
  - pyzmq
  - libgfortran5
  - jupyterlab_pygments
  - six
  - libdeflate
  - flit-core
  - pure_eval
  - importlib-metadata
  - libopenblas
  - matplotlib-base
  - mistune
  - nest-asyncio
  - pygments
  - attrs
  - send2trash
  - libcblas
  - cycler
  - jupyter_console
  - backcall
  - jupyter_core
  - jsonschema
  - python-dateutil
  - testpath
  - freetype
  - pillow
  - jpeg
  - zipp
  - ptyprocess
  - giflib
  - pickleshare
  - packaging
  - ncurses
  - tzdata
  - pandocfilters
  - python_abi
  - wheel
  - libwebp-base
  - jinja2
  - nbformat
  - pthread-stubs
  - libpng
  - munkres
  - cffi
  - backports
  - readline
  - bzip2
  - webencodings
  - stack_data
  - libcxx
  - markupsafe
  - prometheus_client
  - libbrotlicommon
  - jedi
  - libxcb
  - libffi
  - ipython
  - tornado
  - libbrotlienc
  - pyrsistent
  - prompt_toolkit
  - ipywidgets
  - psutil
  - lz4-c
  - fonttools
  - unicodedata2
  - widgetsnbextension
  - libgfortran
  - soupsieve
  - lerc
  - argon2-cffi
  - nbclient
  - debugpy
  - defusedxml
  - zstd
  - jupyter_client
  - brotli-bin
  - kiwisolver
  - libblas
  - pip
  - asttokens
  - beautifulsoup4
  - llvm-openmp
  - bleach
  - setuptools
  - pyparsing
  - jupyterlab_widgets
  - zeromq
  - python-fastjsonschema
  - libbrotlidec
  - libzlib
  - libtiff
  - tk
  - wcwidth
  - nbconvert
  - argon2-cffi-bindings
  - traitlets
  - lcms2
  - xorg-libxdmcp
  - liblapack
  - importlib_resources
  - executing
  - decorator
  - brotli
  - pexpect
  - libwebp
  - openjpeg
  - appnope
  - zlib
  - libsodium
  - terminado
  - ipython_genutils
  - xorg-libxau
  - matplotlib-inline
  - xz
  - notebook
  - prompt-toolkit
  - backports.functools_lru_cache
  - ipykernel
  - pycparser
  - entrypoints
  - parso
  - sqlite
  - pytest
  - line_profiler
  - autopep8
  - joblib
  - shapely
  - networkx
